name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: '22.13.1'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --immutable
      - run: yarn lint:eslint
      - run: yarn lint:prettier
      - run: yarn build
      - run: yarn npm publish
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
